/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeBackRouteImport } from './routes/welcome-back'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InfoRouteImport } from './routes/info'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ToolToolIdRouteImport } from './routes/tool.$toolId'

const WelcomeBackRoute = WelcomeBackRouteImport.update({
  id: '/welcome-back',
  path: '/welcome-back',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolToolIdRoute = ToolToolIdRouteImport.update({
  id: '/tool/$toolId',
  path: '/tool/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/info': typeof InfoRoute
  '/login': typeof LoginRoute
  '/submit': typeof SubmitRoute
  '/trending': typeof TrendingRoute
  '/welcome-back': typeof WelcomeBackRoute
  '/tool/$toolId': typeof ToolToolIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/info': typeof InfoRoute
  '/login': typeof LoginRoute
  '/submit': typeof SubmitRoute
  '/trending': typeof TrendingRoute
  '/welcome-back': typeof WelcomeBackRoute
  '/tool/$toolId': typeof ToolToolIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/info': typeof InfoRoute
  '/login': typeof LoginRoute
  '/submit': typeof SubmitRoute
  '/trending': typeof TrendingRoute
  '/welcome-back': typeof WelcomeBackRoute
  '/tool/$toolId': typeof ToolToolIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/info'
    | '/login'
    | '/submit'
    | '/trending'
    | '/welcome-back'
    | '/tool/$toolId'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/info'
    | '/login'
    | '/submit'
    | '/trending'
    | '/welcome-back'
    | '/tool/$toolId'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/info'
    | '/login'
    | '/submit'
    | '/trending'
    | '/welcome-back'
    | '/tool/$toolId'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InfoRoute: typeof InfoRoute
  LoginRoute: typeof LoginRoute
  SubmitRoute: typeof SubmitRoute
  TrendingRoute: typeof TrendingRoute
  WelcomeBackRoute: typeof WelcomeBackRoute
  ToolToolIdRoute: typeof ToolToolIdRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome-back': {
      id: '/welcome-back'
      path: '/welcome-back'
      fullPath: '/welcome-back'
      preLoaderRoute: typeof WelcomeBackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$toolId': {
      id: '/tool/$toolId'
      path: '/tool/$toolId'
      fullPath: '/tool/$toolId'
      preLoaderRoute: typeof ToolToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InfoRoute: InfoRoute,
  LoginRoute: LoginRoute,
  SubmitRoute: SubmitRoute,
  TrendingRoute: TrendingRoute,
  WelcomeBackRoute: WelcomeBackRoute,
  ToolToolIdRoute: ToolToolIdRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
